image: hummingbirdtest
git:
  path: hummingbird
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin
script:
  - go get -t ./...
  - go test -cover ./...
  - go build
  - service memcached start
  - sudo -u swift swift-init start proxy-server
  - sudo -u swift swift-init start account-server
  - sudo -u swift swift-init start container-server
  - ./hummingbird start object
  - nosetests --exe /home/swift/swift/test/functional
