image: hummingbirdtest
git:
  path: hummingbird
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin
script:
  - make get test install
  - service memcached start
  - sudo -u swift swift-init start proxy-server
  - sudo -u swift swift-init start account-server
  - sudo -u swift swift-init start container-server
  - sudo -u swift hummingbird start object
  - sudo -u swift nosetests --exe /home/swift/swift/test/functional
  - sudo -u swift hummingbird stop object
  - cp -pr /etc/swift/object-server /etc/hummingbird
  - sudo -u swift sed -ri 's/60([0-9]{2})/70\1/' /etc/hummingbird/object-server/*.conf
  - sudo -u swift swift-init start object-server
  - sudo -u swift hummingbird start object
  - ssh-agent bash -c 'ssh-add /root/id_saddle_bird; cd /home/swift; git clone git@github.com:rackerlabs/saddle-bird.git'
  - python /home/swift/saddle-bird/setup.py develop
  - sudo -u swift nosetests --exe /home/swift/saddle-bird
