sudo: required

dist: trusty

language: go

go:
  - 1.9

matrix:
  include:
    - env: HYBRID=YES
    - env: HYBRID=NO

install:
  - sudo apt-get install liberasurecode-dev libjerasure-dev
  - make get all
  - bin/hummingbird init haio
  - ./hummingbird-init-haio.sh skiptests
  - sudo apt remove python-nose # since we'll be installing the pip edition
  - go get github.com/haya14busa/goverage
  - mkdir -p /tmp/output
  - |
    set -e
    if [ "$HYBRID" = "YES" ] ; then
      cd ~/swift
      git checkout stable/pike
    else
      mkdir -p /tmp/output/bin
      cp /usr/bin/hummingbird /tmp/output/bin
    fi
  - virtualenv ~/swift-venv
  - ~/swift-venv/bin/pip install -U pip setuptools python-subunit nose-htmloutput nose-exclude
  - ~/swift-venv/bin/pip install -r ~/swift/requirements.txt
  - ~/swift-venv/bin/pip install -r ~/swift/test-requirements.txt
  - sudo mkdir -p /etc/swift /var/run/swift
  - sudo chown -R "${USER}"  /etc/swift /var/run/swift
  - cp ~/swift/doc/saio/bin/* ~/swift-venv/bin
  - cp -p -r ~/swift/doc/saio/swift/* /etc/swift
  - cp -p /etc/hummingbird/*.ring.gz /etc/swift
  - cp -p ~/swift/test/sample.conf /etc/swift/test.conf
  - cd ~/swift; ~/swift-venv/bin/python setup.py install
  - find /etc/swift -name "*.conf" | xargs sed -i "s/<your-user-name>/${USER}/"
  - sed -i "s/eventlet_debug = true/object_post_as_copy = true/" /etc/swift/proxy-server.conf
  - printf "[swift-hash]\nswift_hash_path_prefix = changeme\nswift_hash_path_suffix = changeme\n" > /etc/swift/swift.conf

script:
  - |
    set -e
    if [ "$HYBRID" = "YES" ] ; then
      hummingbird start object
      hummingbird start container
      hummingbird start account
      PATH=$PATH:~/swift-venv/bin swift-init start proxy
      PATH=$PATH:~/swift-venv/bin nosetests -e test_unicode_metadata --with-html --html-file=/tmp/output/functional_swiftproxy.html ~/swift/test/functional
    else
      test -z "$(find . -name '*.go' | xargs gofmt -l -s)" || (echo "You need to run 'make fmt'"; exit 1)
      go vet github.com/troubling/hummingbird/...
      goverage -coverprofile=/tmp/coverage.out github.com/troubling/hummingbird/...
      go tool cover -html=/tmp/coverage.out -o "/tmp/output/coverage.html"
      hummingbird start main
      PATH=$PATH:~/swift-venv/bin nosetests --with-html --html-file=/tmp/output/functional_hbproxy.html ~/swift/test/functional --exclude-test-file=$TRAVIS_BUILD_DIR/.swift_func_excludes
    fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: /usr/bin/hummingbird
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true
